language: minimal

services:
  - docker

script:
  - docker build -t fin1ger/building-a-distributed-wamp-router:scenario-availability-wamp ./scenarios/availability/wamp
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fin1ger/building-a-distributed-wamp-router:scenario-availability-wamp

  - docker build -t fin1ger/building-a-distributed-wamp-router:scenario-availability-mqtt ./scenarios/availability/mqtt
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fin1ger/building-a-distributed-wamp-router:scenario-availability-mqtt

  - docker build -t fin1ger/building-a-distributed-wamp-router:scenario-ram-usage-wamp ./scenarios/ram-usage/wamp
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fin1ger/building-a-distributed-wamp-router:scenario-ram-usage-wamp

  - docker build -t fin1ger/building-a-distributed-wamp-router:scenario-ram-usage-mqtt ./scenarios/ram-usage/mqtt
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fin1ger/building-a-distributed-wamp-router:scenario-ram-usage-mqtt

  - docker build -t fin1ger/building-a-distributed-wamp-router:scenario-high-load-wamp ./scenarios/high-load/wamp
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fin1ger/building-a-distributed-wamp-router:scenario-high-load-wamp

  - docker build -t fin1ger/building-a-distributed-wamp-router:scenario-high-load-mqtt ./scenarios/high-load/mqtt
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fin1ger/building-a-distributed-wamp-router:scenario-high-load-mqtt

  - docker build -t fin1ger/building-a-distributed-wamp-router:scenario-scaling-out-wamp ./scenarios/scaling-out/wamp
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fin1ger/building-a-distributed-wamp-router:scenario-scaling-out-wamp

  - docker build -t fin1ger/building-a-distributed-wamp-router:scenario-scaling-out-mqtt ./scenarios/scaling-out/mqtt
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fin1ger/building-a-distributed-wamp-router:scenario-scaling-out-mqtt

  - docker run -it --rm -v "$(pwd):/data" aergus/latex /bin/bash -c "cd /data/paper && make pdf"

before_deploy:
  - git tag -f travis-dev-build
  - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push -f gh travis-dev-build
  - git remote remove gh

deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: paper/build/paper.pdf
  skip_cleanup: true
  name: latest paper build
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    branch: master
