apiVersion: v1
kind: ConfigMap
metadata:
  name: crossbar-config
data:
  crossbar-config: |
    {
        "$schema": "https://raw.githubusercontent.com/crossbario/crossbar/master/crossbar.json",
        "version": 2,
        "controller": {
        },
        "workers": [
            {
                "type": "router",
                "realms": [
                    {
                        "name": "default",
                        "roles": [
                            {
                                "name": "anonymous",
                                "permissions": [
                                    {
                                        "uri": "",
                                        "match": "prefix",
                                        "allow": {
                                            "call": true,
                                            "register": true,
                                            "publish": true,
                                            "subscribe": true
                                        },
                                        "disclose": {
                                            "caller": false,
                                            "publisher": false
                                        },
                                        "cache": true
                                    }
                                ]
                            }
                        ]
                    }
                ],
                "transports": [
                    {
                        "type": "universal",
                        "endpoint": {
                            "type": "tcp",
                            "port": 8080
                        },
                        "rawsocket": {
                        },
                        "websocket": {
                            "ws": {
                                "type": "websocket"
                            }
                        },
                        "web": {
                            "paths": {
                                "info": {
                                    "type": "nodeinfo"
                                }
                            }
                        }
                    }
                ]
            }
        ]
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crossbar.fullname" . }}
  labels:
{{ include "crossbar.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "crossbar.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "crossbar.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: crossbario/crossbar:cpy3
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: crossbar-config
              mountPath: /node/.crossbar/config.json
              subPath: config.json
      volumes:
        - name: crossbar-config
          configMap:
            name: crossbar-config
            items:
              - key: crossbar-config
                path: config.json
